#!/bin/bash
# RClone Config file
echo "CRON: Uploading to cloud..."
RCLONE_CONFIG="/config/rclone.conf"
export RCLONE_CONFIG

#exit if running
if [[ "`pidof -x $(basename $0) -o %PPID`" ]]; 
then
  echo "CRON: Already running, exiting."
  exit; 
fi

## wait 30 sec
sleep 2

# Move older local files to the cloud
/usr/bin/rclone move /mnt/cache/ $RemotePath --log-file /opt/rclone/logs/upload.log --exclude-from /opt/rclone/scripts/excludes $MoveCommands


echo "CRON: Upload completed! Refreshing cache..."
# force refresh
/usr/bin/rclone rc vfs/refresh recursive=true | jq -r '.result[]'

echo "CRON: Refresh complete"
